"""add chatbot primary color

Revision ID: 4cd0b3863e30
Revises: f0ed77730141
Create Date: 2026-09-24 21:42:02.313377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd0b3863e30'
down_revision: Union[str, Sequence[str], None] = 'f0ed77730141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'chatbots',
    sa.Column(
        'primary_color',
        sa.String(length=7),
        nullable=False,
        server_default='#111827',
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbots', 'primary_color')
    # ### end Alembic commands ###
