"""add password hash to profiles

Revision ID: 5fd4ed4c3c03
Revises: 415b46faf752
Create Date: 2026-09-14 06:17:01.096966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd4ed4c3c03'
down_revision: Union[str, Sequence[str], None] = '415b46faf752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'password_hash')
    # ### end Alembic commands ###
